language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

env:
    - CI=true
    - TRAVIS=true
    - CONTINUOUS_INTEGRATION=true
    - USER=seezee
    - HOME /Users/chriszahller
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

after_failure:
  - cat MSBuild_*/Users/seezee/Local\ Sites\mercuryphoto⁩/app⁩/⁨public/⁨wp-content⁩ /⁨plugins/wp-foft-loader/.admin/⁩.travis_fail.txt