language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

env:
    - CI=true
    - TRAVIS=true
    - CONTINUOUS_INTEGRATION=true
    - DEBIAN_FRONTEND=noninteractive
    - HAS_JOSH_K_SEAL_OF_APPROVAL=true
    - USER=seezee
    - HOME /Users/chriszahller
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - RAILS_ENV=test
    - RACK_ENV=test
    - MERB_ENV=test
    - JRUBY_OPTS="--server -Dcext.enabled=false -Xcompile.invokedynamic=false"
    - JAVA_HOME
